name: Build BSG-Makeup-BackEnd

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag bsg-makeup-be:$(date +%s)

  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
  
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      - name: Build with Gradle and copy .jar to root directory
        run: |
           ./gradlew build -x test
           cp build/libs/bsg-makeup-be-0.0.1-SNAPSHOT.jar ./app.jar
        
      - name: Deploy to AWS Elastic Beanstalk
        id: deploy
        uses: einaregilsson/beanstalk-deploy@v17
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: bsg-makeup-be-us-west-2-prod
          environment_name: Bsg-makeup-be-us-west-2-prod-env
          version_label: ${{ github.run_id }}_${{ github.sha }}
          region: us-west-2
          deployment_package: app.jar
          wait_for_deployment: false
